[workspace]
resolver = "2"
members = ["dnas/*/integrity_zomes/*", "dnas/*/coordinator_zomes/*"]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace.dependencies]
hdi = "0.2.4"
hdk = "0.1.4"
